version: '3.8'
name: personal-site
services:
  personal-site:
    restart: unless-stopped
    ports:
      - "7000:3000"
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - /storage/docker-state/personal-site/:/usr/src/app
      - /storage/docker-state/jellyfin-stack/media/jellyfin-media/Photos/:/usr/src/app/static/images
    command: sh -c "npm install && npm run build && node build"